### PR TITLE
Compatibility for TYPO3 v10 and minor code improvements

### PR DESCRIPTION
**Pull request by tritum**
* compatiblity for TYPO3 10.4
* fix integration in newContentElement.wizard
* remove usage of $package
* use offically supported file extension for PageTS and TypoScript
* apply CGL to PageTS and TypoScript files
* version bump to 4.2

### CODE REVIEW

**Comment by fnagel** [comment]
@tritum @tritumBj Thanks for the PR! I will merge this this afternoon hopefully. Changes look good in general but I will probably cherry pick instead of merging as I already have some more local changes and prefer rename instead of delete / add. 

Did you eventually have some experience regarding PHP 7.3 (#32) or even PHP 7.4 (#38)? Would be great to include compatibility with the upcoming release.

**Comment by fnagel** [comment]
After some more consideration I've decided not to merge or cherry pick a commit, but I've adopted some of your changes. Please see master branch!

Again, thanks for the contribution and testing!

**Comment by tritum** [comment]
Awesome @fnagel. Thanks for all your effort and working on this PR. Love what you've done. There are some minor issue I have to test. If I cannot fix those I'll create an issue for it. But let's see. I will also ask my colleagues regarding PHP 73. and 7.4.

Thanks again for taking care.
Björn a.k.a tritumBj

**Comment by fnagel** [comment]
@tritum @tritumBj No problem and sorry again for not merging directly. Feedback for PHP would be awesome and I guarantee it will be included in the 10 LTS version (which I plan to release this week).

**Pull request closed without merging**
