### PR TITLE
[TASK] Add TemplateCompiler XCLASS for TYPO3.CMS 7.3.0

### PR DESCRIPTION
**Pull request by dreadwarrior**
Hey Felix,

could you please try out this patch? I'm currently already on 7.3.1 where this issue seems to be fixed (see cherry-pick information at https://review.typo3.org/#/c/40539/2) I've backported the TemplateCompiler into ext:beautyofcode and added that version as an XCLASS.

Hope this works,

tommy

### CODE REVIEW

**Comment by fnagel** [comment]
Tested, makes boc work in 7.3.0 again. I did not check if its fixed in core when using 7.3.1.

Please see my inline comments.

**Comment by dreadwarrior** [comment]
Thanks for reviewing Felix! I'll push a follow up later this day.

Greetings,
tommy

**Comment by dreadwarrior** [comment]
Hey Felix,

so the XCLASS is gone now. I've set the minimum requirement in ext_emconf to TYPO3.CMS 7.3.1.

Best,

tommy

**Comment by dreadwarrior** [comment]
Applied your suggestion. Much better! m)

Best,

tommy

**Comment by fnagel** [comment]
Merged, see 3a2ffedc0153120bc769a7fed03d8d22acf59b08, 3cc45c851e89c6dd6167201af7740e4a796df8a8, 3f3890fbf2802f3dc7032978e18e0c940b6592fb

**Pull request closed without merging**
